[자동차 경주 게임] 희봉 미션 제출합니다.
wootechco-again-level1/racing-car pull request #2
Opened 2019-11-23 03:28 UTC by heebong

안녕하세요 철시! 리뷰를 받게된 희봉입니다.
그저 빛인 철시에게 리뷰 받게 되어 영광입니다.
코딩 너무 어렵네요. 쉽지 않아요..... 😭 
많은 가르침 부탁드립니다 🙇‍♀

2019-11-25 05:03 UTC, pkch93 requested changes
잘 구현하셨네요! :+1:
특히 Spring과 같이 Controller, Service 구조를 갖추고 단위테스트, 통합테스트를 해주신 점에서 한수 배우고 갑니다!

남긴 리뷰는 제 생각을 담은거라 의문이 있거나 논의가 필요하다고 싶은 부분은 말씀주세요 :)

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/controller/RacingCarsController.java
> +public class RacingCarsController {
controller의 역할이 좀 모호한거 같아요. 입력값을 실제로 받고 넘겨주는 역할을 Application에서 하고 있다고 생각이 들었어요!

Application에서 Controller의 역할을 하기 때문에 RacingCarsController에서는 RacingCarsService의 메서드를 부르기만 한다고 생각이 드는데 어떤가요?

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/domain/Car.java
> +    private void validateName(final String name) {
입력값 검증 :+1:

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
Cars가 현재 두가지 역할을 하고 있다고 생각해요.

첫째, 게임에 참여하는 Car들의 이동거리를 체크.
둘째, 최종 우승자를 관리하는 역할.

여기서 두번째 역할에서는 몰라도 될 부분이 Cars에 많이 담겨있다고 생각해요. 따라서 최종 우승자를 관리하는 클래스를 따로 분리하는 건 어때요?

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/domain/Cars.java
> +    public Stream<Car> stream() {
Effective Java 3/E Item 47. 반환타입으로는 스트림보다 컬렉션이 낫다.

[참고](https://jaehun2841.github.io/2019/02/16/effective-java-item47/#%EC%9C%84%EC%9D%98-%EB%82%B4%EC%9A%A9%EA%B3%BC-%EA%B0%99%EC%9D%80-%EB%A1%9C%EC%A7%81-for-loop%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%BD%94%EB%93%9C)

이 메서드를 쓰는 toRaceWinner에서도 Cars를 받으니 cars를 그대로 return 해주는 getter를 만드는게 어떨까요?

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/service/RacingCarsService.java
> +public class RacingCarsService {
cars를 인스턴스 변수로 뺀 이유가 있을까요? RacingCarsService에서는 RacingCars의 생성자로 넣어주기 위해서 선언한 것 같아서요...

RacingCarsService의 로직은 RacingCars로 이뤄지니 racingCars만 가지고 있어도 되지 않나라는 생각을 했어요!

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/racingcar/service/RacingCarsService.java
> +    public void race() {
race 이후의 결과를 void가 아닌 RaceProcessResponse로 리턴하는건 어떤가요??

이 메서드를 사용하는 RacingCarsController에서 race를 하고 바로 getRaceProcess로 리턴해주길래 race 결과를 바로 리턴해주면 어떨까라는 생각을 했어요!

2019-11-25 05:03 UTC, pkch93 commented on src/main/java/strategy/MoveStrategy.java
> +public interface MoveStrategy {
:+1: 이동 방법이 숫자 말고도 다른 방법으로 바뀔 수 있겠네요!

2019-11-25 05:03 UTC, pkch93 commented on src/test/java/racingcar/service/RacingCarsServiceTest.java
> +        service.createCars(requestDto, moveStrategy);
정상 흐름임을 알려줄 수 있도록 assertDoesNotThrow 단언 메서드를 사용하는 것은 어떤가요?

```suggestion
        assertDoesNotThrow(() -> service.createRacingCars(requestDto));
```

2019-11-27 11:16 UTC, heebong commented on src/main/java/racingcar/controller/RacingCarsController.java
> +public class RacingCarsController {
뷰를 컨트롤러에서 호출하지 않고, 컨트롤러의 함수 하나를 api 하나라고 생각해서 나눠서 그렇게되었습니다...ㅠㅠ 컨트롤러에서 뷰를 호출하는게 더 좋을까요?

2019-11-27 11:23 UTC, heebong commented on src/main/java/racingcar/service/RacingCarsService.java
> +public class RacingCarsService {
차 이름(NamesRequestDto)과 횟수(RacingCountRequestDto)가 한 번에 받지 않아서 이렇게 받게 되었습니다. 이름 먼저 받고 도메인 로직에서 체크한 다음에 횟수를 받고싶어서 이렇게 해보았습니다ㅠㅠ

2019-11-27 11:25 UTC, heebong commented on src/main/java/racingcar/service/RacingCarsService.java
> +    public void race() {
더 생각해보니 그게 나을거같네요!!

2019-11-27 12:27 UTC, heebong commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
👍 Winners를 추가했습니다!

2019-11-27 12:34 UTC, heebong commented on src/test/java/racingcar/service/RacingCarsServiceTest.java
> +        service.createCars(requestDto, moveStrategy);
훌륭..! 반영했습니다!

2019-11-27 12:56 UTC, heebong commented on src/main/java/racingcar/domain/Cars.java
> +    public Stream<Car> stream() {
getter를 사용하기 싫어서 이렇게 했는데 이펙티브를 안읽은 티가 여기서 나네요ㅎㅎ
근데 get()을 정말 하기 싫은데... `Iterable`을 상속받는건 구질구질할까요...?ㅎㅎㅎㅠㅠㅠ
상속받는것도 의미가 맞는거같긴 해서...ㅠㅠ 구질구질하네요

2019-11-27 13:26 UTC, pkch93 commented on src/main/java/racingcar/domain/Cars.java
> +    public Stream<Car> stream() {
혹시 getter를 거부(?)하는 이유가 있을까요??
만약 getter를 쓰지 않는다면 차라리 `Iterable`을 사용하는게 나아보이긴 하다고 생각이 들지만 제 생각은 cars 컬랙션을 getter로 반환해주는게 어떨까 생각했어요.

이유는 Effective Java 3/E Item 47에 나오는 내용과 같아요. 컬랙션(리스트)인 cars가 이미 stream 뿐만 아니라 iterator를 반환해주기도 하니깐 이들을 포함하는 cars를 getter로반환해주는게 더 낫지 않나라고 생각했기 때문이에요!

2019-11-27 13:31 UTC, pkch93 commented on src/main/java/racingcar/service/RacingCarsService.java
> +public class RacingCarsService {
아아 무슨 말씀인지 알겠습니다! 혹시 이름이랑 게임 횟수를 함께 받고 Service를 만드는 방법은 어떨까요?? 생성 로직을 생성자 하나로도 만들수 있다고 생각이 들어서요...!

2019-11-27 13:33 UTC, pkch93 commented on src/main/java/racingcar/controller/RacingCarsController.java
> +public class RacingCarsController {
제가 저렇게 생각한 이유는 현 구조에서 Controller가 필요할까 라는 생각이 들어서였어요. 그 증거가 Service의 메서드를 호출만 하기 때문이구요... 그리고 Application이 이미 Controller의 역할을 하고 있기 때문에 현재 Controller의 역할이 모호해졌다고 생각이 들었어요... 이 부분에 대해서는 어떻게 생각하시나요??

2019-11-28 04:32 UTC, pkch93 commented
자동차 경주 게임 고생하셨습니다 :) 서로 많은걸 배운 시간이었길 바랍니다 ~!

2019-11-28 04:32 UTC, merged